const registerTypes = {
  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  GET_REGISTRATION_TOKEN_START: "GET_REGISTRATION_TOKEN_START",
  GET_REGISTRATION_TOKEN_SUCCESS: "GET_REGISTRATION_TOKEN_SUCCESS",
  GET_REGISTRATION_TOKEN_FAILURE: "GET_REGISTRATION_TOKEN_FAILURE",
  GET_POSITIONS_START: "GET_POSITIONS_START",
  GET_POSITIONS_SUCCESS: "GET_POSITIONS_SUCCESS",
  GET_POSITIONS_FAILURE: "GET_POSITIONS_FAILURE",
};

export default registerTypes;
