const registerTypes = {
  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  GET_REGISTRATION_TOKEN_START: "GET_REGISTRATION_TOKEN_START",
  GET_REGISTRATION_TOKEN_SUCCESS: "GET_REGISTRATION_TOKEN_SUCCES",
  GET_REGISTRATION_TOKEN_FAILURE: "GET_REGISTRATION_TOKEN_FAILURE",
};

export default registerTypes;
