const usersTypes = {
  FETCH_INITIAL_USERS_START: "FETCH_INITIAL_USERS_START",
  FETCH_INITIAL_USERS_SUCCESS: "FETCH_INITIAL_USERS_SUCCESS",
  FETCH_INITIAL_USERS_FAILURE: "FETCH_INITIAL_USERS_FAILURE",
  FETCH_MORE_USERS_START: "FETCH_MORE_USERS_START",
  FETCH_MORE_USERS_SUCCESS: "FETCH_MORE_USERS_SUCCESS",
  FETCH_MORE_USERS_FAILURE: "FETCH_MORE_USERS_FAILURE",
};

export default usersTypes;
